Draft of the new manual

diff --git a/SibeliaZ-LCB/sibeliaz b/SibeliaZ-LCB/sibeliaz
--- a/SibeliaZ-LCB/sibeliaz
+++ b/SibeliaZ-LCB/sibeliaz
@@ -1,5 +1,50 @@
 #!/bin/bash
 
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+k=25
+b=200
+m=50
+a=150
+f=5
+threads=1
+infile=
+outdir="./sibeliaz_out"
+align="True"
+
+usage () { echo "Usage: [-k <k>] [-b <integer>] [-m <integer>] [-a <integer>] [-t <integer>] [-f <float>] [-o <output_directory>] <input file> " ;}
+
+options='t:k:b:a:m:f:gh'
+while getopts $options option
+do
+    case $option in
+	k  ) k=$OPTARG;;
+	b  ) b=$OPTARG;;
+	m  ) m=$OPTARG;;
+	a  ) a=$OPTARG;;
+	t  ) threads=$OPTARG;;
+	o  ) outdir=$OPTARG;;
+	f  ) f=$OPTARG;;
+	h  ) usage; exit;;
+	n  ) align="False";;
+	\? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
+	:  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
+	*  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
+    esac
+done
+
+
+shift $((OPTIND-1))
+
+if [ -z "$1" ]
+then
+	echo "You must provide the input file name" >&2
+	exit 1
+fi
+
+min() {
+   [ "$1" -lt "$2" ] && echo $1 || echo $2
+}
+
 align()
 {
         ulimit -m 25600000
@@ -16,7 +61,24 @@ align()
         fi
 }
 
-echo "##maf version=1" > "$3"
 export -f align
-find $1/blocks -name "*.fa" -printf "$PWD/%p\n" | xargs -I @ -P "$2" bash -c "align @ '$3'"
+
+infile=$1
+twopaco_threads=$( min $threads 16 )
+lcb_threads=$( min $threads 4 )
+dbg_file=$outdir/de_bruijn_graph.dbg
+
+mkdir -p $outdir
+/usr/bin/time -f "TwoPaCo %e elapsed %M memory" $DIR/twopaco --tmpdir $outdir -t $twopaco_threads -k $k --filtermemory $f -o $dbg_file $infile
+/usr/bin/time -f "SibeliaZ-LCB %e elapsed %M memory" $DIR/sibeliaz-lcb --graph $dbg_file --fasta $infile -k $k -b $b -o $outdir -m $m -t $lcb_threads --abundance $a
+
+if [ "$align" = "True" ]
+then
+	align_file=$outfile/alignment.maf
+	echo "##maf version=1" > "$alignment_file"
+	find $outfile/blocks -name "*.fa" -printf "$PWD/%p\n" | xargs -I @ -P "$2" bash -c "align @ '$outfile'"
+fi
+
+
+
 
